### ISSUE TITLE
only sudo mode can use the liblightnvm correctly

### ISSUE THREAD

**Issue by NikoKVCS** [OpenChannelSSD/liblightnvm#27]
i compiled the hello.c successfully. codes from http://lightnvm.io/liblightnvm/quick_start/index.html
and when i run it by "./hello", it shows the error "function not implemented"

Then i try again with "sudo ./hello", it shows a correct result.
How can i solve this ?

**Comment by safl** [comment]
Hi Niko,

When using one of the IOCTL based backends, e.g. `NVM_BE_IOCTL` or `NVM_BE_LBD`, then the user must have `CAP_SYS_ADMIN`. This is because the `nvm_dev_open` call, as in in the hello-world-example, is handled by a backend which ends up performing an `ioctl` call to send an NVMe admin command to the drive via the Kernel NVMe driver. And, the Kernel NVMe driver require `CAP_SYS_ADMIN` for sending such commands.

Right now, then there is no way around the `CAP_SYS_ADMIN` requirement. But you can configure it to avoid using `sudo`. For example like this:

```
# Set CAP_SYS_ADMIN on your binary
sudo setcap cap_sys_admin+ep hello
# Let the user own the device
sudo chown $USER:$USER /dev/nvme0n1
```

Previously, liblightnvm had a way to work around this by grabbing the information it needed via SYSFS. This approach is deprecated, but it might be an idea to add something similar again.

For the SPDK based backends then user privileges must be configured/setup for either `vfio` or `uio_generic` to allow for non-root users to access the PCIe device.

Best,
Simon

**Comment by NikoKVCS** [comment]
> Hi Niko,
> 
> When using one of the IOCTL based backends, e.g. `NVM_BE_IOCTL` or `NVM_BE_LBD`, then the user must have `CAP_SYS_ADMIN`. This is because the `nvm_dev_open` call, as in in the hello-world-example, is handled by a backend which ends up performing an `ioctl` call to send an NVMe admin command to the drive via the Kernel NVMe driver. And, the Kernel NVMe driver require `CAP_SYS_ADMIN` for sending such commands.
> 
> Right now, then there is no way around the `CAP_SYS_ADMIN` requirement. But you can configure it to avoid using `sudo`. For example like this:
> 
> ```
> # Set CAP_SYS_ADMIN on your binary
> sudo setcap cap_sys_admin+ep hello
> # Let the user own the device
> sudo chown $USER:$USER /dev/nvme0n1
> ```
> 
> Previously, liblightnvm had a way to work around `CAP_SYS_ADMIN` by grabbing the information it needed via SYSFS. This approach is deprecated, but it might be an idea to add something similar again.
> 
> For the SPDK based backends then user privileges must be configured/setup for either `vfio` or `uio_generic` to allow for non-root users to access the PCIe device.
> 
> Best,
> Simon

Thank you, Simon.
My problem solved a half by the solution you provided.

I tried "sudo setcap cap_sys_admin+ep hello" and "sudo chown $USER:$USER /dev/nvme0n1" and after it i no more have to type "sudo" as you have said.

But new problem is the error "function not implemented" still appeared when in debug mode. 

My project use liblightnvm, and when i debug my project, the error still appear even when i have tried "sudo setcap cap_sys_admin+ep executablefile"
