### ISSUE TITLE
Data not written and duplicate sectors read when using qemu-nvme

### ISSUE THREAD

**Issue by sacheendra** [OpenChannelSSD/liblightnvm#38]
I am trying to read and write four 4096 byte sectors from an OCSSD device emulated by qemu-nvme.
I notice that instead of reading 4 sectors, I just receive 4 copies of the first sector.
Could someone direct me to where the error could most likely be?

The commands I use are:
`dd if=/dev/urandom of=in.data bs=4K count=4`
`sudo nvm_cmd erase /dev/nvme0n1 0x0000000000000000`
`sudo nvm_cmd write /dev/nvme0n1 0x0000000000000000 0x0000000000000001 0x0000000000000002 0x0000000000000003 -i in.data`
`sudo nvm_cmd read /dev/nvme0n1 0x0000000000000000 0x0000000000000001 0x0000000000000002 0x0000000000000003 -o out.data`
`xxd in.data in.hex`
`xxd out.data out.hex`
`diff in.data out.data | less`

I first generate random data, then write it. Later, I read the data and compare them. The diff command shows that the files differ starting at the second sector. The output can also be inspected in a text editor to verify that it contains four copies of the same sector.

I use Ubuntu 20.4 with kernel 5.4. I built qemu-nvme from the master branch. I start qemu with the command
`qemu-system-x86_64 -hda ./ubuntu.img --enable-kvm -m 4G -smp 2 -blockdev ocssd,node-name=nvme01,file.driver=file,file.filename=ocssd.img -device nvme,drive=nvme01,serial=deadbeef,id=lnvm -net user,hostfwd=tcp::7777-:22 -net nic --cpu host -virtfs local,path="$PWD",mount_tag=host0,security_model=none,id=host0 --trace events=qemu_trace_events`

**Comment by safl** [comment]
Hi @sacheendra,

What you are trying to do, should just work. Just as in the example here: http://lightnvm.io/liblightnvm/cli/nvm_cmd.html#submitting-io

Which qemu-emulator are you using? If you point me to the repos and branch that you are using, then I can try reproducing it an help identify what might cause the issue.

Otherwise, have you considered Zoned Namespace instead of Open-Channel SSDs?
For user-space libraries and tooling similar to liblightnvm for Zoned Namespace, and more, have a look at:

https://xnvme.io/
https://github.com/OpenMPDK/xNVMe/

Cheers,
Simon

**Comment by MatiasBjorling** [comment]
If you're thinking of switching to the standardized ZNS SSD interface -

Then you can skip qemu and use null_blk to create a zoned block device for you to use.

You can use the below commands:

SIZE_MB=$((8 * 1024)) 

modprobe null_blk
cd /sys/kernel/config/nullb &&
    mkdir -p conv_nullb &&
    cd conv_nullb ; echo 0 > power; 
    echo 0 > completion_nsec &&
    echo 4096 > blocksize &&
    echo $SIZE_MB > size &&
    echo 1 > memory_backed &&
    echo 1 > power

With that you have a zoned block device. You can now use the blkzone utility (part of the util-linux package) to query zones, reset, etc.

If you like an easy to use programming interface, you can use libzbd (https://github.com/westerndigitalcorporation/libzbd) that has little complexity and is quick to get going.

There's more information on the http://zonedstorage.io website.

Best, Matias

**Comment by sacheendra** [comment]
@safl :

Thanks for the response.
I am using the master branch of https://github.com/OpenChannelSSD/qemu-nvme.

@MatiasBjorling and @safl :

We use the open channel SSD API right now in assignment to teach students how to write custom a custom FTL for their use case. The null_blk method seems like it will be easier for students to use and debug than qemu.

I did not use zoned namespaces because it seemed very new. Is xNVME and thus zoned namespaces stable enough for students to use without gotchas?

**Comment by MatiasBjorling** [comment]
@sacheendra 

Ah, got it.

I can't speak about xNVMe and its maturity, but I can talk about the existing support in the Linux kernel eco-systems that's already available and is used by many in the industry in production.

Generally, the ZNS SSD support in the Linux kernel is built upon the Zoned subsystem, which has been in development since  Linux kernel 4.10. This support was added into Linux kernel 5.9 - but we mostly just added Zone Capacity support, one can easily go back to a 5.4 kernel, and have the functionality needed to build an FTL (either in user-space or kernel space).

The ZNS interface is simpler than OCSSD (by design) - and has less of the complexity that usually follows when using OCSSDs. That was one of the design goals I pushed hard when the ZNS specification was written.

There are many tools already available and have been maturing for many years due to the synergies with the SMR HDD ZAC/ZBD interfaces

https://zonedstorage.io/projects/util-linux/
https://zonedstorage.io/projects/libzbd/

Additionally, we have made a graphical interface that shows the state of each zone, making it easy for the students to visualize what they are doing.

https://zonedstorage.io/projects/libzbd/#graphical-interface

Best, Matias

**Comment by safl** [comment]
@sacheendra 
Regarding the use of xNVMe and ZNS for students.

A lot of text here, going top-down :)

You can get a feel of the xNVMe based command-line tool here:

* https://xnvme.io/docs/latest/tools/zoned/index.html

The tool is implemented using the xNVMe Zoned API (``libznd.h``):

* https://xnvme.io/docs/latest/capis/znd.html

The API is simple and has helper functions for many of the tedious tasks as well as pretty-printers for data-structures.

Also, the source of the cli-tool:

* https://github.com/OpenMPDK/xNVMe/blob/master/tools/zoned.c

serves as an example of using the ``libznd.h`` API as it exercises most of it.
Adding to that, is a dedicated example of setting up asynchronous IO:

* https://github.com/OpenMPDK/xNVMe/blob/master/examples/zoned_io_async.c

So there is a good handful of example code to the management as well as the IO part.

A convenient part of using xNVMe is that it provides a unified API for their FTL to access the lower-layers.
That is, xNVMe implements multiple library-backends encapsulating the use of IOCTLs, libaio, io_uring, and SPDK.
They don't have to worry about that they can focus on the concepts and the FTL logic. But if they want to, they can switch without changing a line of code by prepending the backend name to the device path e.g.:

	# Use the io_uring backend
	zoned_io_async write liou:/dev/nvme0n1

	# Use the libaio backend
	zoned_io_async write laio:/dev/nvme0n1

	# Use the SPDK backend
	zoned_io_async write spdk:0000:01:00.0?nsid=1

To get them started, there is the getting started guide:

* https://xnvme.io/docs/latest/quick_start/index.html

and more detailed instructions on building from source:

* https://xnvme.io/docs/latest/building/index.html

or they can just download the debian-packages or binary archive from the latest release:

* https://github.com/OpenMPDK/xNVMe/releases/tag/v0.0.20

On the device side side, a docker-image is available:

* https://hub.docker.com/repository/docker/refenv/qemu-nvme

It contains qemu with full ZNS support from one of qemu/nvme maintainers tree:

* https://irrelevant.dk/g/pci-nvme.git/

I can highly recommend the switch from OpenChannel to ZNS; the specification is standardized, and the software eco-system is more robust in kernel and user-space. In short, there is a rich set of libraries, tools, and people engaged with ZNS, and if you want to use xNVMe, then I am available and happy to help should you encounter any gotchas, questions, ideas, or feature requests.

If you have any questions to the qemu side of things, then my colleague @birkelund would be happy to answer those as he did the qemu/zns implementation referred to above.

Best,
Simon
